version: 2

sources:
  - name: fivetran_discorama
    schema: google_drive_discorama
    tables:
      - name: actor
      - name: category
      - name: city
      - name: address
      - name: country